services:
  db:
    image: postgres:16
    container_name: RepoMind_DB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - app_db_data:/var/lib/postgresql/
    restart: unless-stopped

volumes:
  app_db_data:
